version: 0.0.5

global:
  env:
    NODE_ENV: production

zoo-frontend:
  image:
    tag: "0.0.0"
  ingress:
    hostTemplate: "zoo-pro.example.com"

zoo-backend:
  image:
    tag: "0.0.0"
  mongo:
    service:
      name: "zoo-pro-mongodb"
  ingress:
    hostTemplate: "api-zoo-pro.example.com"
