global:
  # replicas: 2
  env:
    NODE_ENV: development

zoo-frontend:
  image:
    tag: "0.0.0"
  ingress:
    hostTemplate: "zoo-pre.example.com"

zoo-backend:
  image:
    tag: "0.0.0"
  mongo:
    service:
      name: "zoo-pre-zoo-mongo-svc"
  ingress:
    hostTemplate: "api-zoo-pre.example.com"
