#ENC[AES256_GCM,data:z4F8wUv/uO+Qv7nW3sDjKPKo7FJLzUXyqobpgkJYyqYNTiTBVmQSDslFFCXcQZB18Qw=,iv:4y710aAIhOxYMO5uKUBRRDFxVwgYcx0hvHyRU2FoDng=,tag:5HTA/qTf0VdX/6dDlEIlhQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: zoo-dev-mongodb
    namespace: dev
    labels:
        app.kubernetes.io/instance: zoo-dev
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/version: 7.0.6
        helm.sh/chart: mongodb-15.0.0
        app.kubernetes.io/component: mongodb
type: Opaque
data:
    mongodb-root-password: ENC[AES256_GCM,data:dJWzv/M7eTcdPTiD,iv:sxzPfNyT5/N0dPrTcvDY2jm5QS0LyL0tSM/dmniSGY4=,tag:IHrf18g2kzxQ0s1erBbG4w==,type:str]
    mongodb-passwords: ENC[AES256_GCM,data:2J0Fa11q3d7T52Z6t0tNpA==,iv:GdWAI2Mp0fcQPyaLoVLqFi5AwgiZIYqgo67KRRmBCOU=,tag:FYh52fxR9+XaY5ao42931Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15peyc7pedj8gjqwnarat6s3u87wy4j5xtf7t96vuj74m3l9xq5ys0r4sag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUUdiRDQwZm16MDRnSktM
            b2Z3ZDFPNGsvWU90NjNCNENLV0FQR3o1V2tJCklTVkpReWpHUFdNelpHSjFmV3RI
            WUZqNzZVeEQ4V0dKZ3B0V29QdmVPaDQKLS0tIHdMUzkwM1NaY1JZQ1A1Y0xrUDdV
            N2MzdVFzcFZoL3Q0aXU0THNlVVRUS2cKUh5fVm6V5MYFStyB3M/YmIcYpOKAoxov
            UHXnVLjUmDmP/xyimtv0ci8x9hRrmISbMRB5/UJuI5O/sgZ52dSl3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T16:44:53Z"
    mac: ENC[AES256_GCM,data:1Xah84XDb2Vl+Ifwi4lYx1XOJUe8PnqFti+yXf59S5h+jrkSkMq4HYkpXT3eGLWzDSZjYrGooAfPqEMcNweyFumBDAh4vboQoUfJBsWPzV5d0RzIXxixJS6HYsak7htKvp9PxG5luc8F/T5Xhc8b/Fvlvp6uYKxBLj6fbPuvv7M=,iv:QcEEDKLDrREpKQYgf8wGpI5AXyWflH47F4M0toe+40I=,tag:iLBEzCdUd+uL67fj30TsSQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
---
#ENC[AES256_GCM,data:3ApxmMLA1hdvz3UoHCk33Tz1pFLMuN1kdISMmm8TVnA2UFslMbyMeKOykmdwIlo95cMYyJE=,iv:2H2wRig+J6oZxwMNNifXAFJpAE9MfDxmmAnPmOWbGhE=,tag:D4F727r6KjUGY/iMg8tnmQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: zoo-dev-zoo-backend-secret
    labels:
        app.kubernetes.io/instance: zoo-dev
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:4ncgRPF4jVQxQ31oz0flyRLCwebSn4D3I5zjEu+n+NnaMy11wB43L4SfFn3cG5P3+yGYHtmwBuIb/GrYDaBe72Dn9HGe,iv:WJb7T3hIwhSMOajsVKlx4Ji53sUVRqOjDjnZPwDr+3w=,tag:4VEyJ/inUs9RUGedkBGciw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15peyc7pedj8gjqwnarat6s3u87wy4j5xtf7t96vuj74m3l9xq5ys0r4sag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUUdiRDQwZm16MDRnSktM
            b2Z3ZDFPNGsvWU90NjNCNENLV0FQR3o1V2tJCklTVkpReWpHUFdNelpHSjFmV3RI
            WUZqNzZVeEQ4V0dKZ3B0V29QdmVPaDQKLS0tIHdMUzkwM1NaY1JZQ1A1Y0xrUDdV
            N2MzdVFzcFZoL3Q0aXU0THNlVVRUS2cKUh5fVm6V5MYFStyB3M/YmIcYpOKAoxov
            UHXnVLjUmDmP/xyimtv0ci8x9hRrmISbMRB5/UJuI5O/sgZ52dSl3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T16:44:53Z"
    mac: ENC[AES256_GCM,data:1Xah84XDb2Vl+Ifwi4lYx1XOJUe8PnqFti+yXf59S5h+jrkSkMq4HYkpXT3eGLWzDSZjYrGooAfPqEMcNweyFumBDAh4vboQoUfJBsWPzV5d0RzIXxixJS6HYsak7htKvp9PxG5luc8F/T5Xhc8b/Fvlvp6uYKxBLj6fbPuvv7M=,iv:QcEEDKLDrREpKQYgf8wGpI5AXyWflH47F4M0toe+40I=,tag:iLBEzCdUd+uL67fj30TsSQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
---
#ENC[AES256_GCM,data:KpYfaQCRgRATiIGdD40Q6z/oG2dSyfDxE9Yn8twkvz8ddxLVWW7C,iv:Qgg0PiwzzH9TdeBA2h3n5epdZK1B6D8ubTXWTCMIxRY=,tag:yApt7SB5YBfIAH7N2Br3+A==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:mpHm6ZPz9Wb+k9HKuAa5WKph/s9VmqHv4kXmk7hC8QyXaMi3Flzrhmgcivt9wYhwRJHX+MelS6y930AFxmlgsOzMWJwrvE+kvAqliqwWVvdkj7wNoZCiwzGhBKIO2TTYy/ZUHXRhFeSw8VM8/hBJY7S3hlmzkjPpTChoEJasO06SsXeKbmsF1RPj6fvMYu2U8fSyudZYQxVycEfYtlnIfP9vdQATFC24eatiybgGgR+mP9F7obFi3FRkFb0I7L1zzKyt3RQ8NDoKAzj0lVhnahgKs5k0nipgzVV9Jgzj5XeFlo/ApYLQH+OjUeZn5kNFQiQqR/wlUQxXoBn26aPQs2UnriG+/dleyRHLy6kKoHX81Ggz46BZtHzeEEDbBXqD,iv:nehmsqD6nIshjhbHk5sNxBE8a3FVWJUWXIM/tdYQxbM=,tag:PbiyA/ecswQ3ZFAYSDjgBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15peyc7pedj8gjqwnarat6s3u87wy4j5xtf7t96vuj74m3l9xq5ys0r4sag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUUdiRDQwZm16MDRnSktM
            b2Z3ZDFPNGsvWU90NjNCNENLV0FQR3o1V2tJCklTVkpReWpHUFdNelpHSjFmV3RI
            WUZqNzZVeEQ4V0dKZ3B0V29QdmVPaDQKLS0tIHdMUzkwM1NaY1JZQ1A1Y0xrUDdV
            N2MzdVFzcFZoL3Q0aXU0THNlVVRUS2cKUh5fVm6V5MYFStyB3M/YmIcYpOKAoxov
            UHXnVLjUmDmP/xyimtv0ci8x9hRrmISbMRB5/UJuI5O/sgZ52dSl3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T16:44:53Z"
    mac: ENC[AES256_GCM,data:1Xah84XDb2Vl+Ifwi4lYx1XOJUe8PnqFti+yXf59S5h+jrkSkMq4HYkpXT3eGLWzDSZjYrGooAfPqEMcNweyFumBDAh4vboQoUfJBsWPzV5d0RzIXxixJS6HYsak7htKvp9PxG5luc8F/T5Xhc8b/Fvlvp6uYKxBLj6fbPuvv7M=,iv:QcEEDKLDrREpKQYgf8wGpI5AXyWflH47F4M0toe+40I=,tag:iLBEzCdUd+uL67fj30TsSQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
