#ENC[AES256_GCM,data:6ohrydpc24A1XZ49/S9GRFgutt0S6vBV+KdB1uG+qVb90PHNSAHscC6in4i/tU/+rnE=,iv:0RT39iOyJJj6CU1qMstjdTJ273DWLjoUHsvIEI9FX8I=,tag:AIB0jlN6DFM+D9JgxqCk3A==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: zoo-dev-mongodb
    namespace: dev
    labels:
        app.kubernetes.io/instance: zoo-dev
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/version: 7.0.6
        helm.sh/chart: mongodb-15.0.0
        app.kubernetes.io/component: mongodb
type: Opaque
data:
    mongodb-root-password: ENC[AES256_GCM,data:SuT3v5DXFf8ksBcH,iv:Q2doQK3gt7Db5TzRAi7HaWn04ytQqVpD3SJYghNI9Iw=,tag:uWkcQdhMW3ACg9qkHDfDgw==,type:str]
    mongodb-passwords: ENC[AES256_GCM,data:9vQiipTapUa/dI/aA8Hl7g==,iv:yua7ULA6AXcgMzJiZZLnhm/j/5xYkP4Kk+CG7H9apN8=,tag:4FSQsprw1RxQ2g+zCGo10A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15peyc7pedj8gjqwnarat6s3u87wy4j5xtf7t96vuj74m3l9xq5ys0r4sag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTlBIMVlLR0lMOEVkTmh2
            N3hYb0QyZFVDUDV3U3hPS0hQRy84N2tyeW5ZCmR0T2RoUmppVDU0Sk50ZFBGUnNh
            OUd5MWhORG9lNkFPeVRxOGNDUjE1Wm8KLS0tICtyOFFhU0RqS2d1UWUrOUJsMXhm
            THFUTjRwczlVcE1VNGdYbFBiWUtSUUEK1Go/2WZQ5ZZdfAKsEkoUCPh7k7IRFZO9
            JMhmbfad9Z6mMs33e6f82UYB401LIjpESsrIDi1Z2WEJBFNQvuvoDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T17:52:21Z"
    mac: ENC[AES256_GCM,data:aQMN91eW1vj0NX5gztAzEbqDk9e2SSRFr50qyn2rf6uAndPBMe5IA6LiH7uywr9cIuH0kxaAdz9M/iTL22mfexzWpQhY8xlDmMk1x1LnquGxQG6XTMAWK1Vr7m69qlPaoseFZmaDRzAEoFxB0fVh2Vy4Q21hGJHkhmf36v+1IGQ=,iv:hJ7HUAHWoMfeYwXlggf3/KCqAXv2z/Hnv5H8LM1xZE4=,tag:4GsVS6SlQfd1zOzlGhyzvg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
---
#ENC[AES256_GCM,data:tKOLNNrQo30wWWz3GlJoXnyXzDf29C3wTuKX9HDY9NIadte6rEh6PbcHAqhufOzxrQqAwPw=,iv:w98R1lgG86+eum11cZw/akGZJhFLfj2cZ9/AkzcYKCI=,tag:+k1Ve9f+eEicPf9vSFD0qQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: zoo-dev-zoo-backend-secret
    labels:
        app.kubernetes.io/instance: zoo-dev
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:Bpfm4nUVcsBbrcRs4TvMWJx6Ev8Pa75rIy8xyrmNa+0vL3xhTI7nNV5HdOVEQ7pwy5GTq9/ioOQCnDUCzV0I83qTYtFH,iv:nRTPH+N8qwZbP7HcmjM3frjkT/5X0dyZURT4U3wINIk=,tag:GvUXvzmH7JUy4Mtcz5Zfyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15peyc7pedj8gjqwnarat6s3u87wy4j5xtf7t96vuj74m3l9xq5ys0r4sag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTlBIMVlLR0lMOEVkTmh2
            N3hYb0QyZFVDUDV3U3hPS0hQRy84N2tyeW5ZCmR0T2RoUmppVDU0Sk50ZFBGUnNh
            OUd5MWhORG9lNkFPeVRxOGNDUjE1Wm8KLS0tICtyOFFhU0RqS2d1UWUrOUJsMXhm
            THFUTjRwczlVcE1VNGdYbFBiWUtSUUEK1Go/2WZQ5ZZdfAKsEkoUCPh7k7IRFZO9
            JMhmbfad9Z6mMs33e6f82UYB401LIjpESsrIDi1Z2WEJBFNQvuvoDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T17:52:21Z"
    mac: ENC[AES256_GCM,data:aQMN91eW1vj0NX5gztAzEbqDk9e2SSRFr50qyn2rf6uAndPBMe5IA6LiH7uywr9cIuH0kxaAdz9M/iTL22mfexzWpQhY8xlDmMk1x1LnquGxQG6XTMAWK1Vr7m69qlPaoseFZmaDRzAEoFxB0fVh2Vy4Q21hGJHkhmf36v+1IGQ=,iv:hJ7HUAHWoMfeYwXlggf3/KCqAXv2z/Hnv5H8LM1xZE4=,tag:4GsVS6SlQfd1zOzlGhyzvg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
---
#ENC[AES256_GCM,data:rtJfjHuYZN15WJra95rYKWLyphCLOJpyN5PrDW346DAD+AoO6pfQ,iv:weboHbCH8QFlIKowf2OPdBTF3YJ3ef/UCelsHaO3itM=,tag:PJ6+GkrD6x+sr0t2nEbvnA==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:6+zLExtEEt+FM/VCabt6gBEIaMXcAtmHqzI8n/ZvVwk5yYsG0bkklf1Lmb0itJcqrLO+XEbbBd0D/E6qHISvA4APtOp/KPxi4XbMwypFSyuZFZGO+PL5C8r0gh2kueD0k0u5NXKtz66hG3/L8JXDKuFZdxQ6aFZM6zLkM11fso7twTml3aebo9wZpEjwB89g2A24tnctUpx2mBUapWqssFLc/iHSCo9jYEvHQc0HbelaJ9/lLAnR0decsQKcdtY1Dc0gR1EXsNdV1fe+/dfc/n9S9MJTtG4afFSSsuFNZpVncmwo0IzMIobgXc7vOG4CaAuC5GZxijiA9kY/++mT4GjxdB6GQo0iNquZZkrXthMDfWf6Wp1KIN4i7OchmauW,iv:rJgaHAnd+ObMBcE7QAcLrGtUGcmYQGX4j6XJgehndpI=,tag:uyCW29CN+HQt01325SIpZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15peyc7pedj8gjqwnarat6s3u87wy4j5xtf7t96vuj74m3l9xq5ys0r4sag
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTlBIMVlLR0lMOEVkTmh2
            N3hYb0QyZFVDUDV3U3hPS0hQRy84N2tyeW5ZCmR0T2RoUmppVDU0Sk50ZFBGUnNh
            OUd5MWhORG9lNkFPeVRxOGNDUjE1Wm8KLS0tICtyOFFhU0RqS2d1UWUrOUJsMXhm
            THFUTjRwczlVcE1VNGdYbFBiWUtSUUEK1Go/2WZQ5ZZdfAKsEkoUCPh7k7IRFZO9
            JMhmbfad9Z6mMs33e6f82UYB401LIjpESsrIDi1Z2WEJBFNQvuvoDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T17:52:21Z"
    mac: ENC[AES256_GCM,data:aQMN91eW1vj0NX5gztAzEbqDk9e2SSRFr50qyn2rf6uAndPBMe5IA6LiH7uywr9cIuH0kxaAdz9M/iTL22mfexzWpQhY8xlDmMk1x1LnquGxQG6XTMAWK1Vr7m69qlPaoseFZmaDRzAEoFxB0fVh2Vy4Q21hGJHkhmf36v+1IGQ=,iv:hJ7HUAHWoMfeYwXlggf3/KCqAXv2z/Hnv5H8LM1xZE4=,tag:4GsVS6SlQfd1zOzlGhyzvg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
